### ISSUE TITLE
Error: Value was either too large or too small for a Decimal

### ISSUE THREAD

**Issue by erikmourits** [DevExpress/DevExtreme.AspNet.Data#147]
Hallo,

When I get large values (type of double) back from our database, I'm getting the following error:
```
System.OverflowException: Value was either too large or too small for a Decimal.     
at System.Decimal..ctor(Double value)   
  at System.Double.System.IConvertible.ToDecimal(IFormatProvider provider)     
  at DevExtreme.AspNet.Data.Aggregation.SumAggregator`1.Step(T container, String selector)    
   at DevExtreme.AspNet.Data.Aggregation.AggregateCalculator`1.Step(Object obj, Aggregator`1[] aggregators, String[] selectors) 
       at DevExtreme.AspNet.Data.Aggregation.AggregateCalculator`1.ProcessItem(Object item)
            at DevExtreme.AspNet.Data.Aggregation.AggregateCalculator`1.Run() 
                at DevExtreme.AspNet.Data.DataSourceLoader.Load[T](IQueryable`1 source, DataSourceLoadOptionsBase options)
```
Regards,
Erik

**Comment by AlekseyMartynov** [comment]
Thanks. The fix will be included in `1.3.0-rc5`
