### ISSUE TITLE
Group and Select fail with DevExpress.Xpo LINQ provider

### ISSUE THREAD

**Issue by AlekseyMartynov** [DevExpress/DevExtreme.AspNet.Data#154]
```
Unhandled Exception: System.ArgumentException: 'I0' is not a member of type 'DevExtreme.AspNet.Data.Types.AnonType'

   at System.Linq.Expressions.Expression.ValidateMemberInitArgs(Type type, ReadOnlyCollection`1 bindings)
   at System.Linq.Expressions.Expression.MemberInit(NewExpression newExpression, IEnumerable`1 bindings)
   at System.Linq.Expressions.Expression.MemberInit(NewExpression newExpression, MemberBinding[] bindings)
   at DevExpress.Xpo.XPQueryBase.CreateSubItemCore(Type subType, MemberInitOperator last, CriteriaTypeResolver resolver, ParameterExpression row, Int32& rowIndex)
   at DevExpress.Xpo.XPQueryBase.CreateItemCore(Type type, MemberInitOperator last)
   at DevExpress.Xpo.XPQueryBase.CreateItem(Type type, MemberInitOperator last)
   at DevExpress.Xpo.XPQueryBase.GetData(Type type)
   at DevExpress.Xpo.XPQueryBase.Enumerate(Type type)
   at DevExpress.Xpo.XPQuery`1.GetEnumerator()
   at DevExpress.Xpo.XPQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at DevExtreme.AspNet.Data.GroupHelper`1.Group(IEnumerable`1 data, GroupingInfo groupInfo)
   at DevExtreme.AspNet.Data.GroupHelper`1.Group(IEnumerable`1 data, IEnumerable`1 groupInfo)
   at DevExtreme.AspNet.Data.DataSourceLoaderImpl`1.ContinueWithGrouping[R](IEnumerable`1 loadResult, IAccessor`1 accessor, LoadResult result)
   at DevExtreme.AspNet.Data.DataSourceLoaderImpl`1.Load()
   at DevExtreme.AspNet.Data.DataSourceLoader.Load[T](IQueryable`1 source, DataSourceLoadOptionsBase options)
```

**Comment by AlekseyMartynov** [comment]
The issue is fixed in XPO: https://devexpress.com/issue=T565240

FYI: the workaround was to replace 

```c#
IEnumerable<R> result = source.Provider.CreateQuery<R>(expr);
```

with

```c#
var result = (IEnumerable<R>)source.Provider.CreateQuery(expr);
```
