### ISSUE TITLE
System.ArgumentOutOfRangeException: 'Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index'

### ISSUE THREAD

**Issue by robinNode** [DevExpress/DevExtreme.AspNet.Data#349]
Test steps:
1. when the grid is loaded (default page size is 10)
2. i navigate to the last page 
3. then change the page size to 50 or any number which is greater than 10.
4. then the ArgumentOutOfRangeException comes out.

     dll version: 
     DevExtreme.AspNet.Data 2.2.0

     npm packages:
    "devextreme": "^18.2.7",
    "devextreme-angular": "^18.2.7",
    "devextreme-aspnet-data-nojquery": "^2.2.0",

```
DataSourceLoadOptions
    DefaultSort: null
    Filter: null
    Group: null
    GroupSummary: null
    IsCountQuery: false
    PaginateViaPrimaryKey: true
    PreSelect: null
    PrimaryKey: {string[1]}
    RemoteGrouping: null
    RemoteSelect: null
    RequireGroupCount: false
    RequireTotalCount: true
    Select: null
    Skip: 200
    Sort: null
    StringToLower: null
    Take: 50
    TotalSummary: null
```

```
  System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.Collections.Generic.List`1.System.Collections.IList.get_Item(Int32 index)
   at DevExtreme.AspNet.Data.FilterExpressionCompiler`1.CompileCore(ParameterExpression dataItemExpr, IList criteriaJson)
   at DevExtreme.AspNet.Data.FilterExpressionCompiler`1.Compile(IList criteriaJson)
   at DevExtreme.AspNet.Data.DataSourceExpressionBuilder`1.BuildCore(Expression expr, Boolean paginate, Boolean isCountQuery, Boolean remoteGrouping, IList filterOverride, IReadOnlyList`1 selectOverride)
   at DevExtreme.AspNet.Data.DataSourceLoaderImpl`1.Load()

```

```
<dx-data-grid id="grid" [dataSource]="dataSource" [wordWrapEnabled]="true" [allowColumnReordering]="true"
    height="600" showBorders="true">
    <dxo-paging [pageSize]="10"></dxo-paging>
    <dxo-pager [showPageSizeSelector]="true" [allowedPageSizes]="[10,20,50]"></dxo-pager>
    <dxo-selection mode="multiple"></dxo-selection>
    <dxo-filter-row [visible]="true"></dxo-filter-row>
    <dxo-header-filter [visible]="true"></dxo-header-filter>
    <dxo-group-panel [visible]="true"></dxo-group-panel> 
    <dxo-grouping [autoExpandAll]="false"></dxo-grouping>
    <dxo-remote-operations [sorting]="true" [paging]="true" [filtering]='true' [grouping]='true' [groupPaging]='true'>
    </dxo-remote-operations>
    <dxi-column dataField="id" width="280">
    </dxi-column>
    <dxi-column dataField="parentId" width="280" [allowSearch]="true">
    </dxi-column>
    <dxi-column dataField="displayName" [allowSearch]="true">
    </dxi-column>
    <dxi-column dataField="position" width="75" [allowSearch]="true">
    </dxi-column>
    <dxi-column dataField="type" width="100" [allowSearch]="true">
    </dxi-column>
    <dxi-column dataField="iconId" width="100" [allowSearch]="true">
    </dxi-column>
  </dx-data-grid>
```

**Comment by Bykiev** [comment]
Same here when PaginateViaPrimaryKey is specified, it's happen when number of pages after filtering/grouping/changing datasource is less than selected page.

**Comment by robinNode** [comment]
> Same here when PaginateViaPrimaryKey is specified, it's happen when number of pages after filtering/grouping/changing datasource is less than selected page.

but i have tried the online demo, they don't have this issue. it's so stranger.

**Comment by Bykiev** [comment]
@robinNode, can you please specify the link to the demo?

**Comment by AlekseyMartynov** [comment]
Thanks for reporting.
I'm working on a fix.

**Comment by AlekseyMartynov** [comment]
We plan to release version `2.2.1` shortly.
Temporary blocked on [this AppVeyor issue](https://help.appveyor.com/discussions/problems/23201).

In additionally, my colleague will post a follow up regarding the double request issue mentioned in https://github.com/DevExpress/DevExtreme.AspNet.Data/issues/349#issuecomment-485673810.

**Comment by Bykiev** [comment]
@AlekseyMartynov, AppVeyor issue is resolved, any news when the update will be available on NuGet?

**Comment by AlekseyMartynov** [comment]
Published: https://www.nuget.org/packages/DevExtreme.AspNet.Data/2.2.1
