### ISSUE TITLE
System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'key'))

### ISSUE THREAD

**Issue by crba233** [DevExpress/DevExtreme.AspNet.Data#393]
Hello!

**I'm getting this error:**

System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'key'))

**Here's the relevant libraries:**

EF Core 3.0
DevExtreme.AspNet.Data 2.5.1
AutoMapper 9.0.0

**Here's an extremely simplified example:**

```
class Controller 
{
	private DbContext _dbContext;
	
	public async Task<LoadResult> Get(DataSourceLoadOptions loadOptions) {
		IQueryable<ParentDto> data =
			_dbContext.Parent
				.ProjectTo<ParentDto>();
	        
                // Exception happens here
		return await DataSourceLoader.LoadAsync(data, loadOptions);
	}
}

class ParentDto
{
	public int ParentID { get; set; }
	public int Age { get; set; }
	public List<string> ChildrenNames { get; set; }
	
	public void CreateMappings(Profile configuration)
	{
		configuration.CreateMap<Child, ChildDto>()
			.ForMember(
				dto => dto.ChildrenNames, 
				opt => opt.MapFrom(m => m.Children.Select(x => x.Name))
			);
	}
}

class Parent
{
	public int ParentID { get; set; }
	public int Age { get; set; }
	
	public List<Child> Children { get; set;}
}

class Child
{
	public int ChildID { get; set; }
	public int ParentID { get; set; }
	
	public string Name { get; set; }
}
```

**Here's my DataSourceLoadOptions:**

```
{
   "RequireTotalCount":true,
   "RequireGroupCount":false,
   "IsCountQuery":false,
   "Skip":0,
   "Take":25,
   "Sort":null,
   "Group":null,
   "Filter":null,
   "TotalSummary":[
      {
         "Selector":"Age",
         "SummaryType":"max"
      }
   ],
   "GroupSummary":null,
   "Select":null,
   "PreSelect":null,
   "RemoteSelect":null,
   "RemoteGrouping":null,
   "PrimaryKey":null,
   "DefaultSort":null,
   "StringToLower":null,
   "PaginateViaPrimaryKey":null
}

```

**Here's what is happening:**

It's blowing up while trying to do the aggregation portion to get the max Age.  This only happens when EF Core creates a subselect due to me pulling back all of the Children's Names. 
I don't believe this is related to AutoMapper, but I'm using it so I put that in my example.

**Here's the full stack trace:**

```
System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'key'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.TranslateSum(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitNew(NewExpression newExpression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Translate(SelectExpression selectExpression, Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateSelect(ShapedQueryExpression source, LambdaExpression selector)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToArrayAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at DevExtreme.AspNet.Data.Async.ReflectionAsyncAdapter.<>c__22`1.<InvokeToArrayAsync>b__22_0(Task`1 t)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at DevExtreme.AspNet.Data.DataSourceLoaderImpl`1.ExecRemoteGroupingAsync()
   at DevExtreme.AspNet.Data.DataSourceLoaderImpl`1.ContinueWithAggregationAsync[R](IEnumerable data, IAccessor`1 accessor, LoadResult result)
   at DevExtreme.AspNet.Data.DataSourceLoaderImpl`1.ContinueWithGroupingAsync[R](IEnumerable`1 loadResult, LoadResult result)
   at DevExtreme.AspNet.Data.DataSourceLoaderImpl`1.LoadAsync()
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by crba233** [comment]
I quickly tried to dive into the DataSourceLoaderImpl.LoadAsync code but the only thing I concluded was that the Parameter 'key' object the exception is referencing is probably referring to the 'key' object on your Group class.

**Comment by AlekseyMartynov** [comment]
Hello

The stack trace indicates that the exception is throw inside EF Core's `RelationalSqlTranslatingExpressionVisitor`.

Please try the following query. Does it fail too?

```c#
data
    .GroupBy(obj => new { })
    .Select(g => new {
        I0 = g.Count(),
        I1 = g.Max(obj => obj.Age)
    })
    .ToArray();
```

Workaround:

```c#
loadOptions.RemoteGrouping = false;
```

**Comment by crba233** [comment]
Hi yes,

I actually was just researching that this morning. It seems to be a limitation of EF Core.

Does `loadOptions.RemoteGrouping = false;` work in conjunction with paging?

**Comment by crba233** [comment]
Sorry,

Ignore that last question. I forget that I can just easily test it out.

Better question, what is `loadOptions.RemoteGrouping = false;` doing behind the scenes that's allowing it to work?

**Comment by AlekseyMartynov** [comment]
With `RemoteGrouping = false`, grouping and summaries are executed in memory. Only filter and sorting options are passed to the LINQ provider. For large data, this means increased memory consumption.

I suggest that you post your case to [EF Core issues](https://github.com/aspnet/EntityFrameworkCore/issues) for research.

**Comment by crba233** [comment]
Okay, I appreciate it. Thanks.
