### ISSUE TITLE
DataSourceLoader not working with summaries

### ISSUE THREAD

**Issue by mihey8800** [DevExpress/DevExtreme.AspNet.Data#424]
hello.

I read a lot of docs. Other issues before writing here.
Tryied:
1) options.SerializerSettings.ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore
2) deleted all Big Properties from "Sale" Entity. 
3) deleted all summaries, by big properties. Using only for double NetSalesAmount field.
4) tryied to make simple query like - var sales = db.Sales.AsQuerable(); Without other LINQ.

Nothhing helps.

If i am making . RemoteOperations(o.Filtering(true).Paging(true).GroupPaging(true).Sorting(true).Summary(**false**))
Paginations stops working. Take and Skip are always 0;
If i am deleting summaries from DataGrid, then everithing works, but i need them.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at DevExtreme.AspNet.Data.ExpressionCompiler.CompileAccessorExpression(Expression target, String clientExpr, Action`1 customizeProgression, Boolean liftToNullable)
   at DevExtreme.AspNet.Data.RemoteGrouping.RemoteGroupExpressionCompiler`1.MakeAggregate(Expression aggregateTarget, SummaryInfo s)
   at DevExtreme.AspNet.Data.RemoteGrouping.RemoteGroupExpressionCompiler`1.MakeAggregates(Expression aggregateTarget, IEnumerable`1 summary)+MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at DevExtreme.AspNet.Data.RemoteGrouping.RemoteGroupExpressionCompiler`1.MakeAggregatingProjection(Expression target, Type groupingType, Int32 groupCount)
   at DevExtreme.AspNet.Data.RemoteGrouping.RemoteGroupExpressionCompiler`1.Compile(Expression target)
   at DevExtreme.AspNet.Data.DataSourceExpressionBuilder`1.BuildCore(Expression expr, Boolean paginate, Boolean isCountQuery, Boolean remoteGrouping, IList filterOverride, IReadOnlyList`1 selectOverride)
   at DevExtreme.AspNet.Data.DataSourceLoaderImpl`1.ExecRemoteGroupingAsync()
   at DevExtreme.AspNet.Data.DataSourceLoaderImpl`1.ContinueWithAggregationAsync[R](IEnumerable data, IAccessor`1 accessor, LoadResult result)
   at DevExtreme.AspNet.Data.DataSourceLoaderImpl`1.ContinueWithGroupingAsync[R](IEnumerable`1 loadResult, LoadResult result)
   at DevExtreme.AspNet.Data.DataSourceLoaderImpl`1.LoadAsync()
   at ThSalesReports.Controllers.SalesController.GetSalesByClients(DataSourceLoadOptions loadOptions, String startDate, String endDate, String salesRepId) in D:\thsalesreports\thsalesreports\thsalesreports\Controllers\SalesController.cs:line 737
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at ThSalesReports.UserDestroyerMiddleware.Invoke(HttpContext httpContext, UserManager`1 userManager, SignInManager`1 signInManager) in D:\thsalesreports\thsalesreports\thsalesreports\Startup.cs:line 52
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

```

                        @(Html.DevExtreme().DataGrid<Sale>
                            ()
                            .ID("targets-grid")
                            .DataSource(d =>
                                d.Mvc()
                                    .Controller("Sales")
                                    .LoadAction("GetSalesByClients")
                                    .LoadParams(new { startDate = new JS("function(){return getTargetsStartDate();}"), endDate = new JS("function(){return getTargetsEndDate();}"), salesRepId = new JS("function(){return pickedSalesId;}") })
                                    .UpdateAction("EditSalesRepresantativeTarget")
                                    .Key("Id")
                            )
                            .Columns(columns =>
                            {
                                columns.AddFor(m => m.Customer.Name)
                                    .CssClass("data-grid-column-align-vertical-center dx-accent-cell")
                                    .Caption("Client")
                                    .AllowFiltering(true)
                                    .AllowSorting(true)
                                    .AllowSearch(true)
                                    .AllowEditing(false)
                                    .Alignment(HorizontalAlignment.Center);

                                columns.AddFor(m => m.NetSalesAmount)
                                    .CssClass("data-grid-column-align-vertical-center dx-accent-cell")
                                    .Caption("Sales, THB")
                                    .AllowFiltering(true)
                                    .AllowSorting(true)
                                    .AllowSearch(true)
                                    .Format("#,##0.##")
                                    .AllowEditing(false)
                                    .SortIndex(0)
                                    .SortOrder(SortOrder.Desc)
                                    .AllowHiding(false)
                                    .Alignment(HorizontalAlignment.Center);

                                columns.AddFor(m => m.SalesRepresantativeTarget.TargetInCurrencyByClient)
                                    .CssClass("data-grid-column-align-vertical-center dx-accent-cell")
                                    .Caption("Client Target, THB")
                                    .AllowFiltering(true)
                                    .AllowSorting(true)
                                    .AllowSearch(true)
                                    .AllowEditing(false)
                                    .AllowHiding(false)
                                    .Name("Target")
                                    .Format("#,##0.##")
                                    .Alignment(HorizontalAlignment.Center);

                                columns.Add()
                                    .CssClass("data-grid-column-align-vertical-center dx-accent-cell")
                                    .Caption("Delta, %")
                                    .Name("Delta")
                                    .Format("#,##0.##%")
                                    .CalculateCellValue("getDeltaSalesRepTargets")
                                    .Width(100)
                                    .AllowFiltering(true)
                                    .AllowSorting(true)
                                    .AllowSearch(true)
                                    .AllowEditing(false)
                                    .Alignment(HorizontalAlignment.Center);

                            })
                            .Editing(e => e.Mode(GridEditMode.Cell)
                                .AllowUpdating(false)
                                .AllowDeleting(false)
                                .AllowAdding(false)
                                .UseIcons(true)
                            )
                            .Summary(s => s.TotalItems(items =>
                            {
                                items.AddFor(m => m.NetSalesAmount)
                                    .SummaryType(SummaryType.Sum)
                                    .Name("TotalNetSalesAmount")
                                    .SkipEmptyValues(true)
                                    .ValueFormat("#,##0.##")
                                    .DisplayFormat("TOTAL: {0}");

                                items.AddFor(m => m.SalesRepresantativeTarget.TargetInCurrencyByClient)
                                    .SummaryType(SummaryType.Sum)
                                    .DisplayFormat("{0}")
                                    .ValueFormat("#,##0.##")
                                    .Name("TotalTarget")
                                    .ShowInColumn("Target");

                                items.Add()
                                    .ShowInColumn("Delta")
                                    .Name("TotalAdminDelta")
                                    .SummaryType(SummaryType.Custom)
                                    .SkipEmptyValues(true)
                                    .DisplayFormat("{0}%")
                                    .CssClass("total-delta-value")
                                    .ValueFormat(f => f.Precision(1));
                            }) 
                                .CalculateCustomSummary(@<text>
                                                            function(e)
                                                            {
                                                            getClientsDelta(e);
                                                            }
                                                         </text>)
                            )
                           
                            .OnContentReady("calculateTotalDelta")
                            .SearchPanel(searchPanel => searchPanel
                                .Visible(true)
                                .Placeholder("Search...")
                            )
                            .HeaderFilter(headerFilter => headerFilter.Visible(false))
                            .ColumnHidingEnabled(false)
                            .HoverStateEnabled(true)
                            .ShowBorders(false)
                            .Paging(p => p.Enabled(true).PageSize(20))
                            .FilterRow(f => f.Visible(true))
                            .HeaderFilter(f => f.Visible(true))
                            .GroupPanel(p => p.Visible(true))
                            .Grouping(g => g.AutoExpandAll(false))
                            .RemoteOperations(true)
                            )
```
                        

```
public async Task<object> GetSalesByClients(DataSourceLoadOptions loadOptions, string startDate, string endDate, string salesRepId = null)
{
 var sales = db.Sales
                            .Where(a => a.BillingDate >= DateTime.Parse(startDate) &&
                                        a.BillingDate <= DateTime.Parse(endDate)).GroupBy(g => g.CustomerId).Select(s =>
                                new {customerId = s.Key, total = s.Sum(i => i.NetSalesAmount)}).Select(sale => new Sale
                            {
                                Id = Guid.NewGuid().ToString(),
                                BillingDate = DateTime.Parse(startDate),
                                CustomerId = sale.customerId,
                                NetSalesAmount = sale.total,
                                ProductId = null,
                                SalesRepId = null,
                                CallingUserRole = callerRole,
                                CallingUserId = user.Id
                            }).AsQueryable();

                        return await DataSourceLoader.LoadAsync(sales, loadOptions);
}
```

**Comment by AlekseyMartynov** [comment]
Hello

> If i am making . RemoteOperations(o.Filtering(true).Paging(true).GroupPaging(true).Sorting(true).Summary(**false**))
Paginations stops working. Take and Skip are always 0;

Indeed, remote paging requires that filtering, sorting, and summaries are also remote. This dependency is [described in the documentation](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/remoteOperations/).

Regarding the `NullReferenceException` error, we'll be happy to help. To proceed with our research, we need to analyze the project in which this problem is reproducible. I would appreciate it you share this project or its simplified version with DevExpress support at https://devexpress.com/sc.
