### ISSUE TITLE
Select on nested collections

### ISSUE THREAD

**Issue by zoles** [DevExpress/DevExtreme.AspNet.Data#457]
I use the DevExtreme.AspNet.Data library to process datasource requests on my .NET Core 3 API. I have a problem with the DataSourceLoadOptions.Select expression. 
```json
{
  "data": [
    {
      "Name": "foo",
      "Tasks": [
        {
          "ID": 1,
          "Name": "Name1"
        },
        {
          "ID": 2,
          "Name": "Name2"
        }
      ],
      "OtherItem": {
        "Nested": "bla"
      }
    }
  ]
}
```

It works correctly when I want to return only the OtherItem.Nested item (_select=["OtherItem.Nested"]_), but when I want to achieve the same on a nested collection (_select=["Tasks.ID"]_) I get the following error (the TasksDto contains the ID member):
```
An unhandled exception has occurred while executing the request. System.ArgumentException: 'ID' is not a member of type 'System.Collections.Generic.List`1[TasksDto]' (Parameter 'propertyOrFieldName')
   at System.Linq.Expressions.Expression.PropertyOrField(Expression expression, String propertyOrFieldName)
   at DevExtreme.AspNet.Data.ExpressionCompiler.CompileAccessorExpression(Expression target, String clientExpr, Action`1 customizeProgression, Boolean liftToNullable)
   at DevExtreme.AspNet.Data.SelectExpressionCompiler.<>c__DisplayClass4_0.<Compile>b__0(String i)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at DevExtreme.AspNet.Data.SelectExpressionCompiler.Compile(Expression target, IEnumerable`1 clientExprList, Boolean useNew)
   at DevExtreme.AspNet.Data.SelectExpressionCompiler.Compile(Expression target, IEnumerable`1 clientExprList)
   at DevExtreme.AspNet.Data.DataSourceExpressionBuilder.AddSelect(IReadOnlyList`1 selectOverride)
   at DevExtreme.AspNet.Data.DataSourceExpressionBuilder.BuildLoadExpr(Boolean paginate, IList filterOverride, IReadOnlyList`1 selectOverride)
   at DevExtreme.AspNet.Data.DataSourceLoaderImpl`1.LoadAsync()
```
 Is select supported on nested collections? If so, could you recommend a workaround how I can achieve my desired result?

**Comment by AlekseyMartynov** [comment]
Hello

> Is select supported on nested collections?

No, it isn't. Load options only work on object, not collections.

> could you recommend a workaround 

One option is to perform this transformation on the DTO level, so that `TasksDto.Tasks` is a collection of numbers.

Another options is to use an advanced (and poorly documented) feature [`CustomAccessorCompilers`](https://devexpress.github.io/DevExtreme.AspNet.Data/net/api/DevExtreme.AspNet.Data.Helpers.CustomAccessorCompilers.html). You'll need to know how to work with [C# expression trees](https://docs.microsoft.com/dotnet/csharp/programming-guide/concepts/expression-trees/).

Add this code to Global.asax or the `Configure` method of Startup.cs:

```c#
DevExtreme.AspNet.Data.Helpers.CustomAccessorCompilers.Register((expr, accessorText) =>
{
    if (accessorText == "Tasks.ID")
    {
        var collectionExpr = Expression.Property(expr, "Tasks");

        var lambdaParam = Expression.Parameter(typeof(TasksDto));
        var lambdaExpr = Expression.Lambda(
            Expression.PropertyOrField(lambdaParam, "ID"),
            lambdaParam
        );

        return Expression.Call(
            typeof(Enumerable), "Select",
            new[] { typeof(TasksDto), typeof(int) },
            collectionExpr, lambdaExpr
        );
    }
    return null;
});
```

The load result will look like this:
```json
{
  "data": [
    {
      "Tasks": { "ID": [ 1, 2 ] } 
    }
  ]
}
```
